version: "1"
rules:
  - base: master             # Required. Target branch
    upstream: ARMmbed:master # Required. Must be in the same fork network.
    mergeMethod: hardreset   # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: true      # Optional, merge pull request even when the mergeable_state is not clean. Default: false
    
  - base: feature-cmake-object-libraries
    upstream: ARMmbed:feature-cmake-object-libraries
    mergeMethod: hardreset 
    mergeUnstable: true
    
    # feature-cmake-object-libraries, with uwrt fixes
  - base: uwrt
    upstream: feature-cmake-object-libraries
    mergeMethod: rebase 
    mergeUnstable: true
    assignees:              # Optional
      - wmmc88
      - cindyli-13
    reviewers:              # Optional
      - cindyli-13
      - younesr1
    conflictReviewers:      # Optional, on merge conflict assign a reviewer
      - wmmc88
      - cindyli-13
      
label: ":arrow_heading_down: pull"  # Optional
conflictLabel: "merge-conflict"     # Optional, on merge conflict assign a custom label, Default: merge-conflict
